-- Human-written public-domain tales. See STORY_SOURCES.txt for attribution and changes.
-- Generated from stories.txt; source wording verified by tools/story_sources.py.
local _,ns=...
ns.Stories={
 {id="pd_golden_arm",title="The Golden Arm",premise="",zone="Any campfire",edition="public-domain",openingMode="emote",emotes={},introductions={},lines={
  "There was once a man who travelled the land all over in search of a wife. He saw young and old, rich and poor, pretty and plain, and could not meet with one to his mind.",
  "At last he found a woman, young, fair, and rich, who possessed a right arm of solid gold. He married her at once, and thought no man so fortunate as he was.",
  "They lived happily together, but, though he wished people to think otherwise, he was fonder of the golden arm than of all his wife's gifts besides. At last she died.",
  "The husband put on the blackest black, and pulled the longest face at the funeral; but for all that he got up in the middle of the night, dug up the body, and cut off the golden arm.",
  "He hurried home to hide his treasure, and thought no one would know. The following night he put the golden arm under his pillow, and was just falling asleep, when the ghost of his dead wife glided into the room.",
  "Stalking up to the bedside it drew the curtain, and looked at him reproachfully.",
  "Pretending not to be afraid, he spoke to the ghost, and said: \"What hast thou done with thy cheeks so red?\" \"All withered and wasted away,\" replied the ghost, in a hollow tone.",
  "\"What hast thou done with thy red rosy lips?\" \"All withered and wasted away.\" \"What hast thou done with thy golden hair?\" \"All withered and wasted away.\" \"What hast thou done with thy Golden Arm?\" \"THOU HAST IT!\"",
 }},
 {id="pd_hand_of_glory",title="The Hand of Glory",premise="",zone="Any campfire",edition="public-domain",openingMode="emote",emotes={},introductions={},lines={
  "One dark night, when all was shut up, there came a tap at the door of a lone inn in the middle of a barren moor.",
  "The door was opened, and there stood without, shivering and shaking, a poor beggar, his rags soaked with rain, and his hands white with cold.",
  "He asked piteously for a lodging, and it was cheerfully granted him; there was not a spare bed in the house, but he could lie on the mat before the kitchen fire, and welcome.",
  "So this was settled, and everyone in the house went to bed except the cook, who from the back kitchen could see into the large room through a pane of glass let into the door.",
  "She watched the beggar, and saw him, as soon as he was left alone, draw himself up from the floor, seat himself at the table, extract from his pocket a brown withered human hand, and set it upright in the candlestick.",
  "He then anointed the fingers, and applying a match to them, they began to flame. Filled with horror, the cook rushed up the back stairs, and endeavoured to arouse her master and the men of the house.",
  "But all was in vain--they slept a charmed sleep; so in despair she hastened down again, and placed herself at her post of observation.",
  "She saw the fingers of the hand flaming, but the thumb remained unlighted, because one inmate of the house was awake.",
  "The beggar was busy collecting the valuables around him into a large sack, and having taken all he cared for in the large room, he entered another. On this the woman ran in, and, seizing the light, tried to extinguish the flames.",
  "But this was not so easy. She blew at them, but they burnt on as before. She poured the dregs of a beer-jug over them, but they blazed up the brighter.",
  "As a last resource, she caught up a jug of milk, and dashed it over the four lambent flames, and they died out at once. Uttering a loud cry, she rushed to the door of the apartment the beggar had entered, and locked it.",
  "The whole family was aroused, and the thief easily secured and hanged.",
 }},
 {id="pd_dead_mother",title="The Dead Mother",premise="",zone="Any campfire",edition="public-domain",openingMode="emote",emotes={},introductions={},lines={
  "In a certain village there lived a husband and wife--lived happily, lovingly, peaceably. All their neighbors envied them; the sight of them gave pleasure to honest folks.",
  "Well, the mistress bore a son, but directly after it was born she died. The poor moujik moaned and wept. Above all he was in despair about the babe. How was he to nourish it now? how to bring it up without its mother?",
  "He did what was best, and hired an old woman to look after it. Only here was a wonder! all day long the babe would take no food, and did nothing but cry; there was no soothing it anyhow.",
  "But during (a great part of) the night one could fancy it wasn't there at all, so silently and peacefully did it sleep.",
  "\"What's the meaning of this?\" thinks the old woman; \"suppose I keep awake to-night; may be I shall find out.\" Well, just at midnight she heard some one quietly open the door and go up to the cradle.",
  "The babe became still, just as if it was being suckled. The next night the same thing took place, and the third night, too. Then she told the moujik about it. He called his kinsfolk together, and held counsel with them.",
  "They determined on this; to keep awake on a certain night, and to spy out who it was that came to suckle the babe. So at eventide they all lay down on the floor, and beside them they set a lighted taper hidden in an earthen pot.",
  "At midnight the cottage door opened. Some one stepped up to the cradle. The babe became still. At that moment one of the kinsfolk suddenly brought out the light.",
  "They looked, and saw the dead mother, in the very same clothes in which she had been buried, on her knees besides the cradle, over which she bent as she suckled the babe at her dead breast.",
  "The moment the light shone in the cottage she stood up, gazed sadly on her little one, and then went out of the room without a sound, not saying a word to anyone.",
  "All those who saw her stood for a time terror-struck; and then they found the babe was dead.",
 }},
 {id="pd_frau_trude",title="Frau Trude",premise="",zone="Any campfire",edition="public-domain",openingMode="emote",emotes={},introductions={},lines={
  "There was once a little girl who was obstinate and inquisitive, and when her parents told her to do anything, she did not obey them, so how could she fare well?",
  "One day she said to her parents, \"I have heard so much of Frau Trude, I will go to her some day.",
  "People say that everything about her does look so strange, and that there are such odd things in her house, that I have become quite curious!\" Her parents absolutely forbade her, and said, \"Frau Trude is a bad woman, who does wicked things,",
  "and if thou goest to her; thou art no longer our child.\" But the maiden did not let herself be turned aside by her parent's prohibition, and still went to Frau Trude.",
  "And when she got to her, Frau Trude said, \"Why art thou so pale?\" \"Ah,\" she replied, and her whole body trembled, \"I have been so terrified at what I have seen.\" \"What hast thou seen?\" \"I saw a black man on your steps.\" \"That was a",
  "collier.\" \"Then I saw a green man.\" \"That was a huntsman.\" \"After that I saw a blood-red man.\" \"That was a butcher.\" \"Ah, Frau Trude, I was terrified; I looked through the window and saw not you, but, as I verily believe, the devil himself",
  "with a head of fire.\" \"Oho!\" said she, \"then thou hast seen the witch in her proper costume.",
  "I have been waiting for thee, and wanting thee a long time already; thou shalt give me some light.\" Then she changed the girl into a block of wood, and threw it into the fire.",
  "And when it was in full blaze she sat down close to it, and warmed herself by it, and said, \"That shines bright for once in a way.\"",
 }},
 {id="pd_coffin_lid",title="The Coffin-Lid",premise="",zone="Any campfire",edition="public-domain",openingMode="emote",emotes={},introductions={},lines={
  "A moujik was driving along one night with a load of pots. His horse grew tired, and all of a sudden it came to a standstill alongside of a graveyard.",
  "The moujik unharnessed his horse and set it free to graze; meanwhile he laid himself down on one of the graves. But somehow he didn't go to sleep. He remained lying there some time.",
  "Suddenly the grave began to open beneath him: he felt the movement and sprang to his feet.",
  "The grave opened, and out of it came a corpse--wrapped in a white shroud, and holding a coffin lid--came out and ran to the church, laid the coffin-lid at the door, and then set off for the village. The moujik was a daring fellow.",
  "He picked up the coffin-lid and remained standing beside his cart, waiting to see what would happen. After a short delay the dead man came back, and was going to snatch up his coffin-lid--but it was not to be seen.",
  "Then the corpse began to track it out, traced it up to the moujik, and said: \"Give me my lid: if you don't, I'll tear you to bits!\" \"And my hatchet, how about that?\" answers the moujik.",
  "\"Why, it's I who'll be chopping you into small pieces!\" \"Do give it back to me, good man!\" begs the corpse.",
  "\"I'll give it when you tell me where you've been and what you've done.\" \"Well, I've been in the village, and there I've killed a couple of youngsters.\" \"Well then, now tell me how they can be brought back to life.\" The corpse reluctantly",
  "made answer: \"Cut off the left skirt of my shroud, and take it with you. When you come into the house where the youngsters were killed, pour some live coals into a pot and put the piece of the shroud in with them, and then lock the door.",
  "The lads will be revived by the smoke immediately.\" The moujik cut off the left skirt of the shroud, and gave up the coffin-lid. The corpse went to its grave--the grave opened.",
  "But just as the dead man was descending into it, all of a sudden the cocks began to crow, and he hadn't time to get properly covered over. One end of the coffin-lid remained sticking out of the ground.",
  "The moujik saw all this and made a note of it. The day began to dawn; he harnessed his horse and drove into the village. In one of the houses he heard cries and wailing. In he went--there lay two dead lads.",
  "\"Don't cry,\" says he, \"I can bring them to life!\" \"Do bring them to life, kinsman,\" say their relatives. \"We'll give you half of all we possess.\" The moujik did everything as the corpse had instructed him, and the lads came back to life.",
  "Their relatives were delighted, but they immediately seized the moujik and bound him with cords, saying: \"No, no, trickster! We'll hand you over to the authorities.",
  "Since you knew how to bring them back to life, maybe it was you who killed them!\" \"What are you thinking about, true believers! Have the fear of God before your eyes!\" cried the moujik.",
  "Then he told them everything that had happened to him during the night. Well, they spread the news through the village; the whole population assembled and swarmed into the graveyard.",
  "They found out the grave from which the dead man had come out, they tore it open, and they drove an aspen stake right into the heart of the corpse, so that it might no more rise up and slay.",
  "But they rewarded the moujik richly, and sent him away home with great honor.",
 }},
 {id="pd_sarah_polgrain",title="Sarah Polgrain",premise="",zone="Westfall coast",edition="public-domain",openingMode="emote",emotes={},introductions={},lines={
  "A woman, who had lived in Moonbrook, was executed at Stormwind for the murder of her husband.",
  "There was but little doubt that she had been urged on to the diabolical deed by a horse-dealer, known as Westfall Jack, with whom, for a long period, she was generally supposed to have been criminally acquainted.",
  "Now, it will be remembered that this really happened within the present century. One morning, during my residence in Booty Bay, an old woman from Moonbrook called on me with some trifling message.",
  "While she was waiting for my answer, I made some ordinary remark about the weather. \"It's all owing to Sarah Polgrain,\" said she.",
  "\"Sarah Polgrain,\" said I; \"and who is Sarah Polgrain?\" Then the voluble old lady told me the whole story of the poisoning with which we need not, at present, concern ourselves.",
  "By and by the tale grew especially interesting, and there I resume it. Sarah had begged that Westfall Jack might accompany her to the scaffold when she was led forth to execution.",
  "This was granted; and on the dreadful morning there stood this unholy pair, the fatal beam on which the woman's body was in a few minutes to swing, before them. They kissed each other, and whispered words passed between them.",
  "The executioner intimated that the moment of execution had arrived, and that they must part. Sarah Polgrain, looking earnestly into the man's eyes, said: \"You will?\" Westfall Jack replied, \"I will!\" and they separated.",
  "The man retired amongst the crowd, the woman was soon a dead corpse, pendulating in the wind. Years passed on, Westfall Jack was never the same man as before, his whole bearing was altered. His bold, his dashing air deserted him.",
  "He walked, or rather wandered, slowly about the streets of the town, or the lanes of the country.",
  "He constantly moved his head from side to side, looking first over one, and then over the other shoulder, as though dreading that someone was following him. The stout man became thin, his ruddy cheeks more pale, and his eyes sunken.",
  "At length he disappeared, and it was discovered--for Westfall Jack had made a confidant of some Moonbrook man--that he had pledged himself, \"living or dead, to become the husband of Sarah Polgrain, after the lapse of years.\" To escape, if",
  "possible, from himself, Jack had gone to sea in the merchant service. Well, the period had arrived when this unholy promise was to be fulfilled. Westfall Jack was returning from the Great Sea in a fruit-ship.",
  "He was met by the devil and Sarah Polgrain far out at sea, off Longshore. Jack would not accompany them willingly, so they followed the ship for days, during all which time she was involved in a storm.",
  "Eventually Jack was washed from the deck by such a wave as the oldest sailor had never seen; and presently, amidst loud thunders and flashing lightnings, riding as it were in a black cloud, three figures were seen passing onward.",
  "These were the devil, Sarah Polgrain, and Westfall Jack; and this was the cause of the storm. \"It is all true, as you may learn if you will inquire,\" said the old woman; \"for many of her kin live in Moonbrook.\"",
 }},
 {id="pd_headless_princess",title="The Headless Princess",premise="",zone="Any campfire",edition="public-domain",openingMode="emote",emotes={},introductions={},lines={
  "In a certain country there lived a King; and this King had a daughter who was an enchantress.",
  "Near the royal palace there dwelt a priest, and the priest had a boy of ten years old, who went every day to an old woman to learn reading and writing.",
  "Now it happened one day that he came away from his lessons late in the evening, and as he passed by the palace he looked in at one of the windows. At that window the Princess happened to be sitting and dressing herself.",
  "She took off her head, lathered it with soap, washed it with clean water, combed its hair, plaited its long back braid, and then put it back again in its proper place. The boy was lost in wonder. \"What a clever creature!\" thinks he.",
  "\"A downright witch!\" And when he got home he began telling every one how he had seen the Princess without her head.",
  "All of a sudden the King's daughter fell grievously ill, and she sent for her father, and strictly enjoined him, saying-- \"If I die, make the priest's son read the psalter over me three nights running.\" The Princess died; they placed her in",
  "a coffin, and carried it to church.",
  "Then the king summoned the priest, and said-- \"Have you got a son?\" \"I have, your majesty.\" \"Well then,\" said the King, \"let him read the psalter over my daughter three nights running.\" The priest returned home, and told his son to get",
  "ready. In the morning the priest's son went to his lessons, and sat over his book looking ever so gloomy. \"What are you unhappy about?\" asked the old woman. \"How can I help being unhappy, when I'm utterly done for?\" \"Why what's the matter?",
  "Speak out plainly.\" \"Well then, granny, I've got to read psalms over the princess, and, do you know, she's a witch!\" \"I knew that before you did! But don't be frightened, there's a knife for you.",
  "When you go into the church, trace a circle round you; then read away from your psalter and don't look behind you. Whatever happens there, whatever horrors may appear, mind your own business and go on reading, reading.",
  "But if you look behind you, it will be all over with you!\" In the evening the boy went to the church, traced a circle round him with the knife, and betook himself to the psalter. Twelve o'clock struck.",
  "The lid of the coffin flew up; the Princess arose, leapt out, and cried-- \"Now I'll teach you to go peeping through my windows, and telling people what you saw!\" She began rushing at the priest's son, but she couldn't anyhow break into the",
  "circle. Then she began to conjure up all sorts of horrors. But in spite of all that she did, he went on reading and reading, and never gave a look round.",
  "And at daybreak the Princess rushed at her coffin, and tumbled into it at full length, all of a heap. The next night everything went on just the same.",
  "The priest's son wasn't a bit afraid, went on reading without a stop right up to daybreak, and in the morning went to the old woman. She asked him-- \"Well! have you seen horrors?\" \"Yes, granny!\" \"It will be still more horrible this time.",
  "Here's a hammer for you and four nails.",
  "Knock them into the four corners of the coffin, and when you begin reading the psalter, stick up the hammer in front of you.\" In the evening the priest's son went to the church, and did everything just as the old woman had told him.",
  "Twelve o'clock struck, the coffin lid fell to the ground, the Princess jumped up and began tearing from side to side, and threatening the youth. Then she conjured up horrors, this time worse than before.",
  "It seemed to him as if a fire had broken out in the church; all the walls were wrapped in flames! But he held his ground and went on reading, never once looking behind him.",
  "Just before daybreak the Princess rushed to her coffin--then the fire seemed to go out immediately, and all the deviltry vanished!",
  "In the morning the King came to the church, and saw that the coffin was open, and in the coffin lay the princess, face downwards. \"What's the meaning of all this?\" says he. The lad told him everything that had taken place.",
  "Then the king gave orders that an aspen stake should be driven into his daughter's breast, and that her body should be thrust into a hole in the ground. But he rewarded the priest's son with a heap of money and various lands.",
 }},
 {id="pd_warlock",title="The Warlock",premise="",zone="Any campfire",edition="public-domain",openingMode="emote",emotes={},introductions={},lines={
  "There was once a Moujik, and he had three married sons. He lived a long while, and was looked upon by the village as a Koldun [or wizard].",
  "When he was about to die, he gave orders that his sons' wives should keep watch over him [after his death] for three nights, taking one night apiece; that his body should be placed in the outer chamber, and that his sons' wives should spin",
  "wool to make him a caftan. He ordered, moreover, that no cross should be placed upon him, and that none should be worn by his daughters-in-law.",
  "Well, that same night the eldest daughter-in-law took her seat beside him with some grey wool, and began spinning. Midnight arrives.",
  "Says the father-in-law from his coffin: \"Daughter-in-law, art thou there?\" She was terribly frightened, but answered, \"I am.\" \"Art thou sitting?\" \"I sit.\" \"Dost thou spin?\" \"I spin.\" \"Grey wool?\" \"Grey.\" \"For a caftan?\" \"For a caftan.\" He",
  "made a movement towards her.",
  "Then a second time he asked again-- \"Daughter-in-law, art thou there?\" \"I am.\" \"Art thou sitting?\" \"I sit.\" \"Dost thou spin?\" \"I spin.\" \"Grey wool?\" \"Grey.\" \"For a caftan?\" \"For a caftan.\" She shrank into the corner.",
  "He moved again, came a couple of yards nearer her. A third time he made a movement. She offered up no prayer. He strangled her, and then lay down again in his coffin.",
  "His sons removed her body, and next evening, in obedience to his paternal behest, they sent another of his daughters-in-law to keep watch. To her just the same thing happened: he strangled her as he had done the first one.",
  "But the third was sharper than the other two. She declared she had taken off her cross, but in reality she kept it on. She took her seat and spun, but said prayers to herself all the while. Midnight arrives.",
  "Says her father-in-law from his coffin-- \"Daughter-in-law, art thou there?\" \"I am,\" she replies.",
  "\"Art thou sitting?\" \"I sit.\" \"Dost thou spin?\" \"I spin.\" \"Grey wool?\" \"Grey.\" \"For a caftan?\" \"For a caftan.\" Just the same took place a second time. The third time, just as he was going to rush at her, she laid the cross upon him.",
  "He fell down and died. She looked into the coffin; there lay ever so much money. The father-in-law wanted to take it away with him, or, at all events, that only some one who could outdo him in cunning should get it.",
 }},
 {id="pd_shroud",title="The Shroud",premise="",zone="Any campfire",edition="public-domain",openingMode="emote",emotes={},introductions={},lines={
  "In a certain village there was a girl who was lazy and slothful, hated working but would gossip and chatter away like anything. Well, she took it into her head to invite the other girls to a spinning party.",
  "For in the villages, as every one knows, it is the lazybones who gives the spinning-feast, and the sweet-toothed are those who go to it. Well, on the appointed night she got her spinners together.",
  "They span for her, and she fed them and feasted them. Among other things they chatted about was this--which of them all was the boldest?",
  "Says the lazybones (lezhaka): \"I'm not afraid of anything!\" \"Well then,\" say the spinners, \"if you're not afraid, go past the graveyard to the church, take down the holy picture from the door, and bring it here.\" \"Good, I'll bring it; only",
  "each of you must spin me a distaff-ful.\" That was just her sort of notion: to do nothing herself, but to get others to do it for her. Well, she went, took down the picture, and brought it home with her.",
  "Her friends all saw that sure enough it was the picture from the church. But the picture had to be taken back again, and it was now the midnight hour. Who was to take it? At length the lazybones said: \"You girls go on spinning.",
  "I'll take it back myself. I'm not afraid of anything!\" So she went and put the picture back in its place. As she was passing the graveyard on her return, she saw a corpse in a white shroud, seated on a tomb.",
  "It was a moonlight night; everything was visible. She went up to the corpse, and drew away its shroud from it. The corpse held its peace, not uttering a word; no doubt the time for it to speak had not come yet.",
  "Well, she took the shroud and went home.",
  "\"There!\" says she, \"I've taken back the picture and put it in its place; and, what's more, here's a shroud I took away from a corpse.\" Some of the girls were horrified; others didn't believe what she said, and laughed at her.",
  "But after they had supped and lain down to sleep, all of a sudden the corpse tapped at the window and said: \"Give me my shroud! Give me my shroud!\" The girls were so frightened they didn't know whether they were alive or dead.",
  "But the lazybones took the shroud, went to the window, opened it, and said: \"There, take it.\" \"No,\" replied the corpse, \"restore it to the place you took it from.\" Just then the cocks suddenly began to crow. The corpse disappeared.",
  "Next night, when the spinners had all gone home to their own houses, at the very same hour as before, the corpse came, tapped at the window, and cried: \"Give me my shroud!\" Well, the girl's father and mother opened the window and offered",
  "him his shroud. \"No,\" says he, \"let her take it back to the place she took it from.\" \"Really now, how could one go to a graveyard with a corpse? What a horrible idea!\" she replied. Just then the cocks crew. The corpse disappeared.",
  "Next day the girl's father and mother sent for the priest, told him the whole story, and entreated him to help them in their trouble. \"Couldn't a service be performed?\" they said.",
  "The priest reflected awhile; then he replied: \"Please to tell her to come to church to-morrow.\" Next day the lazybones went to church. The service began, numbers of people came to it.",
  "But just as they were going to sing the cherubim song, there suddenly arose, goodness knows whence, so terrible a whirlwind that all the congregation fell flat on their faces.",
  "And it caught up that girl, and then flung her down on the ground. The girl disappeared from sight; nothing was left of her but her back hair.",
 }},
 {id="pd_two_corpses",title="The Two Corpses",premise="",zone="Any campfire",edition="public-domain",openingMode="emote",emotes={},introductions={},lines={
  "A soldier had obtained leave to go home on furlough--to pray to the holy images, and to bow down before his parents.",
  "And as he was going his way, at a time when the sun had long set, and all was dark around, it chanced that he had to pass by a graveyard.",
  "Just then he heard that some one was running after him, and crying: \"Stop! you can't escape!\" He looked back and there was a corpse running and gnashing its teeth.",
  "The Soldier sprang on one side with all his might to get away from it, caught sight of a little chapel, and bolted straight into it.",
  "There wasn't a soul in the chapel, but stretched out on a table there lay another corpse, with tapers burning in front of it.",
  "The Soldier hid himself in a corner, and remained there, hardly knowing whether he was alive or dead, but waiting to see what would happen. Presently up ran the first corpse--the one that had chased the Soldier--and dashed into the chapel.",
  "Thereupon the one that was lying on the table jumped up, and cried to it: \"What hast thou come here for?\" \"I've chased a soldier in here, so I'm going to eat him.\" \"Come now, brother! he's run into my house.",
  "I shall eat him myself.\" \"No, I shall!\" \"No, I shall!\" And they set to work fighting; the dust flew like anything. They'd have gone on fighting ever so much longer, only the cocks began to crow.",
  "Then both the corpses fell lifeless to the ground, and the Soldier went on his way homeward in peace, saying: \"Glory be to Thee, O Lord! I am saved from the wizards!\"",
 }},
 {id="pd_mr_miacca",title="Mr. Miacca",premise="",zone="Any campfire",edition="public-domain",openingMode="emote",emotes={},introductions={},lines={
  "Tommy Grimes was sometimes a good boy, and sometimes a bad boy; and when he was a bad boy, he was a very bad boy. Now his mother used to say to him: \"Tommy, Tommy, be a good boy, and don't go out of the street, or else Mr.",
  "Miacca will take you.\" But still when he was a bad boy he would go out of the street; and one day, sure enough, he had scarcely got round the corner, when Mr.",
  "Miacca did catch him and popped him into a bag upside down, and took him off to his house. When Mr. Miacca got Tommy inside, he pulled him out of the bag and set him down, and felt his arms and legs.",
  "\"You're rather tough,\" says he; \"but you're all I've got for supper, and you'll not taste bad boiled. But body o' me, I've forgot the herbs, and it's bitter you'll taste without herbs. Sally! Here, I say, Sally!\" and he called Mrs. Miacca.",
  "So Mrs. Miacca came out of another room and said: \"What d'ye want, my dear?\" \"Oh, here's a little boy for supper,\" said Mr. Miacca, \"and I've forgot the herbs. Mind him, will ye, while I go for them.\" \"All right, my love,\" says Mrs.",
  "Miacca, and off he goes. Then Tommy Grimes said to Mrs. Miacca: \"Does Mr. Miacca always have little boys for supper?\" \"Mostly, my dear,\" said Mrs.",
  "Miacca, \"if little boys are bad enough, and get in his way.\" \"And don't you have anything else but boy-meat? No pudding?\" asked Tommy. \"Ah, I loves pudding,\" says Mrs. Miacca.",
  "\"But it's not often the likes of me gets pudding.\" \"Why, my mother is making a pudding this very day,\" said Tommy Grimes, \"and I am sure she'd give you some, if I ask her. Shall I run and get some?\" \"Now, that's a thoughtful boy,\" said Mrs.",
  "Miacca, \"only don't be long and be sure to be back for supper.\" So off Tommy pelters, and right glad he was to get off so cheap; and for many a long day he was as good as good could be, and never went round the corner of the street.",
  "But he couldn't always be good; and one day he went round the corner, and as luck would have it, he hadn't scarcely got round it when Mr. Miacca grabbed him up, popped him in his bag, and took him home. When he got him there, Mr.",
  "Miacca dropped him out; and when he saw him, he said: \"Ah, you're the youngster what served me and my missus that shabby trick, leaving us without any supper. Well, you shan't do it again. I'll watch over you myself.",
  "Here, get under the sofa, and I'll set on it and watch the pot boil for you.\" So poor Tommy Grimes had to creep under the sofa, and Mr. Miacca sat on it and waited for the pot to boil.",
  "And they waited, and they waited, but still the pot didn't boil, till at last Mr.",
  "Miacca got tired of waiting, and he said: \"Here, you under there, I'm not going to wait any longer; put out your leg, and I'll stop your giving us the slip.\" So Tommy put out a leg, and Mr.",
  "Miacca got a chopper, and chopped it off, and pops it in the pot. Suddenly he calls out: \"Sally, my dear, Sally!\" and nobody answered. So he went into the next room to look out for Mrs.",
  "Miacca, and while he was there, Tommy crept out from under the sofa and ran out of the door. For it was a leg of the sofa that he had put out.",
  "So Tommy Grimes ran home, and he never went round the corner again till he was old enough to go alone.",
 }},
 {id="pd_master_pupil",title="The Master and His Pupil",premise="",zone="Any campfire",edition="public-domain",openingMode="emote",emotes={},introductions={},lines={
  "There was once a very learned man in the north-country who knew all the languages under the sun, and who was acquainted with all the mysteries of creation.",
  "He had one big book bound in black calf and clasped with iron, and with iron corners, and chained to a table which was made fast to the floor; and when he read out of this book, he unlocked it with an iron key, and none but he read from it,",
  "for it contained all the secrets of the spiritual world.",
  "It told how many angels there were in heaven, and how they marched in their ranks, and sang in their quires, and what were their several functions, and what was the name of each great angel of might.",
  "And it told of the demons, how many of them there were, and what were their several powers, and their labours, and their names, and how they might be summoned, and how tasks might be imposed on them, and how they might be chained to be as",
  "slaves to man. Now the master had a pupil who was but a foolish lad, and he acted as servant to the great master, but never was he suffered to look into the black book, hardly to enter the private room.",
  "One day the master was out, and then the lad, as curious as could be, hurried to the chamber where his master kept his wondrous apparatus for changing copper into gold, and lead into silver, and where was his mirror in which he could see",
  "all that was passing in the world, and where was the shell which when held to the ear whispered all the words that were being spoken by anyone the master desired to know about.",
  "The lad tried in vain with the crucibles to turn copper and lead into gold and silver--he looked long and vainly into the mirror; smoke and clouds passed over it, but he saw nothing plain, and the shell to his ear produced only indistinct",
  "murmurings, like the breaking of distant seas on an unknown shore.",
  "\"I can do nothing,\" he said; \"as I don't know the right words to utter, and they are locked up in yon book.\" He looked round, and, see! the book was unfastened; the master had forgotten to lock it before he went out.",
  "The boy rushed to it, and unclosed the volume. It was written with red and black ink, and much of it he could not understand; but he put his finger on a line and spelled it through.",
  "At once the room was darkened, and the house trembled; a clap of thunder rolled through the passage and the old room, and there stood before him a horrible, horrible form, breathing fire, and with eyes like burning lamps.",
  "It was the demon Beelzebub, whom he had called up to serve him. \"Set me a task!\" said he, with a voice like the roaring of an iron furnace. The boy only trembled, and his hair stood up.",
  "\"Set me a task, or I shall strangle thee!\" But the lad could not speak. Then the evil spirit stepped towards him, and putting forth his hands touched his throat. The fingers burned his flesh.",
  "\"Set me a task!\" \"Water yon flower,\" cried the boy in despair, pointing to a geranium which stood in a pot on the floor.",
  "Instantly the spirit left the room, but in another instant he returned with a barrel on his back, and poured its contents over the flower; and again and again he went and came, and poured more and more water, till the floor of the room was",
  "ankle-deep. \"Enough, enough!\" gasped the lad; but the demon heeded him not; the lad didn't know the words by which to send him away, and still he fetched water. It rose to the boy's knees and still more water was poured.",
  "It mounted to his waist, and Beelzebub still kept on bringing barrels full. It rose to his armpits, and he scrambled to the table-top.",
  "And now the water in the room stood up to the window and washed against the glass, and swirled around his feet on the table. It still rose; it reached his breast.",
  "In vain he cried; the evil spirit would not be dismissed, and to this day he would have been pouring water, and would have drowned all Duskwood.",
  "But the master remembered on his journey that he had not locked his book, and therefore returned, and at the moment when the water was bubbling about the pupil's chin, rushed into the room and spoke the words which cast Beelzebub back into",
  "his fiery home.",
 }},
 {id="pd_rose_tree",title="The Rose-Tree",premise="",zone="Any campfire",edition="public-domain",openingMode="emote",emotes={},introductions={},lines={
  "There was once upon a time a good man who had two children: a girl by a first wife, and a boy by the second. The girl was as white as milk, and her lips were like cherries. Her hair was like golden silk, and it hung to the ground.",
  "Her brother loved her dearly, but her wicked stepmother hated her.",
  "\"Child,\" said the stepmother one day, \"go to the grocer's shop and buy me a pound of candles.\" She gave her the money; and the little girl went, bought the candles, and started on her return. There was a stile to cross.",
  "She put down the candles whilst she got over the stile. Up came a dog and ran off with the candles. She went back to the grocer's, and she got a second bunch. She came to the stile, set down the candles, and proceeded to climb over.",
  "Up came the dog and ran off with the candles. She went again to the grocer's, and she got a third bunch; and just the same happened.",
  "Then she came to her stepmother crying, for she had spent all the money and had lost three bunches of candles. The stepmother was angry, but she pretended not to mind the loss.",
  "She said to the child: \"Come, lay your head on my lap that I may comb your hair.\" So the little one laid her head in the woman's lap, who proceeded to comb the yellow silken hair.",
  "And when she combed the hair fell over her knees, and rolled right down to the ground.",
  "Then the stepmother hated her more for the beauty of her hair; so she said to her, \"I cannot part your hair on my knee, fetch a billet of wood.\" So she fetched it.",
  "Then said the stepmother, \"I cannot part your hair with a comb, fetch me an axe.\" So she fetched it.",
  "\"Now,\" said the wicked woman, \"lay your head down on the billet whilst I part your hair.\" Well! she laid down her little golden head without fear; and whist! down came the axe, and it was off. So the mother wiped the axe and laughed.",
  "Then she took the heart and liver of the little girl, and she stewed them and brought them into the house for supper. The husband tasted them and shook his head. He said they tasted very strangely.",
  "She gave some to the little boy, but he would not eat.",
  "She tried to force him, but he refused, and ran out into the garden, and took up his little sister, and put her in a box, and buried the box under a rose-tree; and every day he went to the tree and wept, till his tears ran down on the box.",
  "One day the rose-tree flowered. It was spring, and there among the flowers was a white bird; and it sang, and sang, and sang like an angel out of heaven.",
  "Away it flew, and it went to a cobbler's shop, and perched itself on a tree hard by; and thus it sang, \"My wicked mother slew me, My dear father ate me, My little brother whom I love Sits below, and I sing above Stick, stock, stone dead.\"",
  "\"Sing again that beautiful song,\" asked the shoemaker.",
  "\"If you will first give me those little red shoes you are making.\" The cobbler gave the shoes, and the bird sang the song; then flew to a tree in front of a watchmaker's, and sang: \"My wicked mother slew me, My dear father ate me, My little",
  "brother whom I love Sits below, and I sing above Stick, stock, stone dead.\" \"Oh, the beautiful song! sing it again, sweet bird,\" asked the watchmaker.",
  "\"If you will give me first that gold watch and chain in your hand.\" The jeweller gave the watch and chain.",
  "The bird took it in one foot, the shoes in the other, and, after having repeated the song, flew away to where three millers were picking a millstone.",
  "The bird perched on a tree and sang: \"My wicked mother slew me, My dear father ate me, My little brother whom I love Sits below, and I sing above Stick!\" Then one of the men put down his tool and looked up from his work, \"Stock!\" Then the",
  "second miller's man laid aside his tool and looked up, \"Stone!\" Then the third miller's man laid down his tool and looked up, \"Dead!\" Then all three cried out with one voice: \"Oh, what a beautiful song!",
  "Sing it, sweet bird, again.\" \"If you will put the millstone round my neck,\" said the bird.",
  "The men did what the bird wanted and away to the tree it flew with the millstone round its neck, the red shoes in one foot, and the gold watch and chain in the other. It sang the song and then flew home.",
  "It rattled the millstone against the eaves of the house, and the stepmother said: \"It thunders.\" Then the little boy ran out to see the thunder, and down dropped the red shoes at his feet.",
  "It rattled the millstone against the eaves of the house once more, and the stepmother said again: \"It thunders.\" Then the father ran out and down fell the chain about his neck.",
  "In ran father and son, laughing and saying, \"See, what fine things the thunder has brought us!\" Then the bird rattled the millstone against the eaves of the house a third time; and the stepmother said: \"It thunders again, perhaps the",
  "thunder has brought something for me,\" and she ran out; but the moment she stepped outside the door, down fell the millstone on her head; and so she died.",
 }},
 {id="pd_death_sign",title="The Death Sign",premise="",zone="Any campfire",edition="public-domain",openingMode="emote",emotes={},introductions={},lines={
  "A woman was out one day looking after her sheep in the valley, and coming by a little stream she sat down to rest, when suddenly she seemed to hear the sound of low music, and turning round, beheld at some distance a crowd of people dancing",
  "and making merry. And she grew afraid and turned her head away not to see them. Then close by her stood a young man, pale and strange looking, and she beheld him with fear.",
  "\"Who are you?\" she said at last; \"and why do you stand beside me?\" \"You ought to know me,\" he replied, \"for I belong to this place; but make haste now and come away, or evil will befall you.\" Then she stood up and was going away with him,",
  "when the crowd left off their dancing and ran towards them crying-- \"Come back; come back; come back!\" \"Don't stop; don't listen,\" said the young man, \"but follow me.\" Then they both began to run, and ran on until they reached a hillock.",
  "\"Now we are safe,\" said he; \"they can't harm us here.\" And when they stopped he said to her again, \"Look me in the face and say if you know me now?\" \"No,\" she answered, \"you are a stranger to me.\" \"Look again,\" he said, \"look me straight in",
  "the face and you will know me.\" Then she looked, and knew instantly that he was a man who had been drowned the year before in the dark winter time, and the waves had never cast up his body on the shore.",
  "And she threw up her arms and cried aloud-- \"Have you news of my child? Have you seen her, my fair-haired girl, that was stolen from me this day seven years?",
  "Will she come back to me never no more?\" \"I have seen her,\" said the man, \"but she will never come back, never more, for she has eaten of the fairy food and must now stay with the spirits under the sea, for she belongs to them body and",
  "soul. But go home now, for it is late, and evil is near you; and perhaps you will meet her sooner than you think.\" Then as the women turned her face homeward, the man disappeared and she saw him no more.",
  "When at last she reached the threshold of her house a fear and trembling came on her, and she called to her husband that some one stood in the doorway and she could not pass.",
  "And with that she fell down on the threshold on her face, but spake no word more. And when they lifted her up she was dead.",
 }},
 {id="pd_dead_hand",title="The Dead Hand",premise="",zone="Any campfire",edition="public-domain",openingMode="emote",emotes={},introductions={},lines={
  "Witchcraft is sometimes practised by the people to produce butter in the churn, the most efficacious being to stir the milk round with the hand of a dead man, newly taken from the churchyard; but whoever is suspected of this practice is",
  "looked upon with great horror and dread by the neighbours. A woman of the mainland got married to a fine young fellow of one of the islands.",
  "She was a tall, dark woman who seldom spoke, and kept herself very close and reserved from every one.",
  "But she minded her business; for she had always more butter to bring to market than any one else, and could therefore undersell the other farmers' wives.",
  "Then strange rumours got about concerning her, and the people began to whisper among themselves that something was wrong, and that there was witchcraft in it, especially as it was known that whenever she churned she went into an inner room",
  "off the kitchen, shut the door close, and would allow no one to enter.",
  "So they determined to watch and find out the secret, and one day a girl from the neighbourhood, when the woman was out, got in through a window and hid herself under the bed, waiting there patiently till the churning began.",
  "At last in came the woman, and having carefully closed the door began her work with the milk, churning in the usual way without any strange doings that might seem to have magic in them.",
  "But presently she stopped, and going over to a box unlocked it, and from this receptacle, to the girl's horror, she drew forth the hand of a dead man, with which she stirred the milk round and round several times, going down on her knees",
  "and muttering an incantation all the while. Seven times she stirred the milk with the dead hand, and seven times she went round the churn on her knees muttering some strange charm.",
  "After this she rose up and began to gather the butter from the churn with the dead hand, filling a pail with as much butter as the milk of ten cows.",
  "When the pail was quite full she dipped the dead hand three times in the milk, then dried it and put it back again in the box.",
  "The girl, as soon as she could get away unperceived, fled in horror from the room, and spread the news amongst the people.",
  "At once a crowd gathered round the house with angry cries and threats to break open the door to search for the dead hand.",
  "At last the woman appeared calm and cold as usual, and told them they were taking a deal of trouble about nothing, for there was no dead hand in the house.",
  "However, the people rushed in and searched, but all they saw was a huge fire on the hearth, though the smell of burning flesh was distinctly perceptible, and by this they knew that she had burnt the dead hand.",
  "Yet this did not save her from the vengeance of the neighbours.",
  "She was shunned by every one; no one would eat with her, or drink with her, or talk to her, and after a while she and her husband quitted the island and were never more heard of.",
  "However, after she left and the butter was brought to the market, all the people had their fair and equal rights again, of which the wicked witchcraft of the woman had defrauded them for so long, and there was great rejoicing in the island",
  "over the fall and punishment of the wicked witch of the dead hand.",
 }},
 {id="pd_dead_soldier",title="The Dead Soldier",premise="",zone="Any campfire",edition="public-domain",openingMode="emote",emotes={},introductions={},lines={
  "There is an island in the Southfury River, and if a mermaid is seen sitting on the rocks in the sunshine, the people know that a crime has been committed somewhere near; for she never appears but to announce ill-luck, and she has a spite",
  "against mortals, and rejoices at their misfortunes.",
  "One day a young fisherman was drawn by the current towards the island, and he came on a long streak of red blood, and had to sail his boat through it till he reached the rocks where the mermaid was seated; and then the boat went round and",
  "round as in a whirlpool, and sank down at last under the waves. Still he did not lose consciousness.",
  "He looked round and saw that he was in a beautiful country, with tall plants growing all over it; and the mermaid came and sang sweetly to him, and offered him wine to drink, but he would not taste it, for it was red like blood.",
  "Then he looked down, and to his horror he saw a soldier lying on the floor with his throat cut; and all round him was a pool of blood, and he remembered no more till he found himself again in his boat drifting against a hurricane, and",
  "suddenly he was dashed upon a rock, where his friends who were in search of him found him, and carried him home.",
  "There he heard a strange thing: a soldier, a deserter from the Orgrimmar Barracks, being pursued had cut his throat and flung himself over the bridge into the river; and this was the very man the young fisher had seen lying a corpse in the",
  "mermaid's cave.",
  "After this he had no peace or comfort till he went to the priest, who exorcised him and gave him absolution; and then the wicked siren of the rocks troubled him no more, though she still haunts the islands of the Southfury River and tries",
  "to lure victims to their death.",
 }},
 {id="pd_lady_witch",title="The Lady Witch",premise="",zone="Any campfire",edition="public-domain",openingMode="emote",emotes={},introductions={},lines={
  "About a hundred years ago there lived a woman in Duskwood, of whom all the neighbours were afraid, for she had always plenty of money, though no one knew how she came by it; and the best of eating and drinking went on at her house, chiefly",
  "at night--meat and fowls and Dalaran wines in plenty for all comers. And when people asked how it all came, she laughed and said, \"I have paid for it,\" but would tell them no more.",
  "So the word went through the county that she had sold herself to the Evil One, and could have everything she wanted by merely wishing and willing, and because of her riches they called her \"The Lady Witch.\" She never went out but at night,",
  "and then always with a bridle and whip in her hand; and the sound of a horse galloping was heard often far on in the night along the roads near her house.",
  "Then a strange story was whispered about, that if a young man drank of her Dalaran wines at supper and afterwards fell asleep, she would throw the bridle over him and change him to a horse, and ride him all over the country, and whatever",
  "she touched with her whip became hers. Fowls, or butter, or wine, or the new-made cakes--she had but to wish and will and they were carried by spirit hands to her house, and laid in her larder.",
  "Then when the ride was done, and she had gathered enough through the country of all she wanted, she took the bridle off the young man, and he came back to his own shape and fell asleep; and when he awoke he had no knowledge of all that had",
  "happened, and the Lady Witch bade him come again and drink of her Dalaran wines as often as it pleased him. Now there was a fine brave young fellow in the neighbourhood, and he determined to make out the truth of the story.",
  "So he often went back and forwards, and made friends with the Lady Witch, and sat down to talk to her, but always on the watch.",
  "And she took a great fancy to him and told him he must come to supper some night, and she would give him the best of everything, and he must taste her Dalaran wine.",
  "So she named the night, and he went gladly, for he was filled with curiosity.",
  "And when he arrived there was a beautiful supper laid, and plenty of wine to drink; and he ate and drank, but was cautious about the wine, and spilled it on the ground from his glass when her head was turned away.",
  "Then he pretended to be very sleepy, and she said-- \"My son, you are weary.",
  "Lie down there on the bench and sleep, for the night is far spent, and you are far from your home.\" So he lay down as if he were quite dead with sleep, and closed his eyes, but watched her all the time.",
  "And she came over in a little while and looked at him steadily, but he never stirred, only breathed the more heavily.",
  "Then she went softly and took the bridle from the wall, and stole over to fling it over his head; but he started up, and, seizing the bridle, threw it over the woman, who was immediately changed into a spanking grey mare.",
  "And he led her out and jumped on her back and rode away as fast as the wind till he came to the forge.",
  "\"Ho, smith,\" he cried, \"rise up and shoe my mare, for she is weary after the journey.\" And the smith got up and did his work as he was bid, well and strong.",
  "Then the young man mounted again, and rode back like the wind to the house of the Witch; and there he took off the bridle, and she immediately regained her own form, and sank down in a deep sleep.",
  "But as the shoes had been put on at the forge without saying the proper form of words, they remained on her hands and feet, and no power on earth could remove them.",
  "So she never rose from her bed again, and died not long after of grief and shame.",
  "And not one in the whole country would follow the coffin of the Lady Witch to the grave; and the bridle was burned with fire, and of all her riches nothing was left but a handful of ashes, and this was flung to the four points of earth and",
  "the four winds of heaven; so the enchantment was broken and the power of the Evil One ended.",
 }},
 {id="pd_fairy_changeling",title="The Fairy Changeling",premise="",zone="Any campfire",edition="public-domain",openingMode="emote",emotes={},introductions={},lines={
  "One evening, a man was coming home late, and he passed a house where two women stood by a window, talking.",
  "\"I have left the dead child in the cradle as you bid me,\" said one woman, \"and behold here is the other child, take it and let me go;\" and she laid down an infant on a sheet by the window, who seemed in a secret sleep, and it was draped all",
  "in white. \"Wait,\" said the other, \"till you have had some food, and then take it to the fairy queen, as I promised, in place of the dead child that we have laid in the cradle by the nurse.",
  "Wait also till the moon rises, and then you shall have the payment which I promised.\" They then both turned from the window. Now the man saw that there was some devil's magic in it all.",
  "And when the women turned away he crept up close to the open window and put his hand in and seized the sleeping child and drew it out quietly without ever a sound.",
  "Then he made off as fast as he could to his own home, before the women could know anything about it, and handed the child to his mother's care.",
  "Now the mother was angry at first, but when he told her the story, she believed him, and put the baby to sleep--a lovely, beautiful boy with a face like an angel.",
  "Next morning there was a great commotion in the village, for the news spread that the first-born son of the great lord of the place, a lovely, healthy child, died suddenly in the night, without ever having had a sign of sickness.",
  "When they looked at him in the morning, there he laid dead in his cradle, and he was shrunk and wizened like a little old man, and no beauty was seen on him any more.",
  "So great lamentation was heard on all sides, and the whole country gathered to the wake. Amongst them came the young man who had carried off the child, and when he looked on the little wizened thing in the cradle he laughed.",
  "Now the parents were angry at his laughter, and wanted to turn him out. But he said, \"Wait, put down a good fire,\" and they did so.",
  "Then he went over to the cradle and said to the hideous little creature, in a loud voice before all the people-- \"If you don't rise up this minute and leave the place, I will burn you on the fire; for I know right well who you are, and",
  "where you came from.\" At once the child sat up and began to grin at him; and made a rush to the door to get away; but the man caught hold of it and threw it on the fire.",
  "And the moment it felt the heat it turned into a black kitten, and flew up the chimney and was seen no more. Then the man sent word to his mother to bring the other child, who was found to be the true heir, the lord's own son.",
  "So there was great rejoicing, and the child grew up to be a great lord himself, and when his time came, he ruled well over the estate; and his descendants are living to this day, for all things prospered with him after he was saved from the",
  "fairies.",
 }},
 {id="pd_dance_dead",title="The Dance of the Dead",premise="",zone="Any campfire",edition="public-domain",openingMode="emote",emotes={},introductions={},lines={
  "It is especially dangerous to be out late on the last night of November, for it is the closing scene of the revels--the last night when the dead have leave to dance on the hill with the fairies, and after that they must all go back to their",
  "graves and lie in the chill, cold earth, without music or wine till the next November comes round, when they all spring up again in their shrouds and rush out into the moonlight with mad laughter.",
  "One November night, a woman of Fenris Isle, coming home late at the hour of the dead, grew tired and sat down to rest, when presently a young man came up and talked to her.",
  "\"Wait a bit,\" he said, \"and you will see the most beautiful dancing you ever looked on there by the side of the hill.\" And she looked at him steadily. He was very pale, and seemed sad.",
  "\"Why are you so sad?\" she asked, \"and as pale as if you were dead?\" \"Look well at me,\" he answered. \"Do you not know me?\" \"Yes, I know you now,\" she said. \"You are young Brien that was drowned last year when out fishing.",
  "What are you here for?\" \"Look,\" he said, \"at the side of the hill and you will see why I am here.\" And she looked, and saw a great company dancing to sweet music; and amongst them were all the dead who had died as long as she could",
  "remember--men, women, and children, all in white, and their faces were pale as the moonlight.",
  "\"Now,\" said the young man, \"run for your life; for if once the fairies bring you into the dance you will never be able to leave them any more.\" But while they were talking, the fairies came up and danced round her in a circle, joining their",
  "hands. And she fell to the ground in a faint, and knew no more till she woke up in the morning in her own bed at home. And they all saw that her face was pale as the dead, and they knew that she had got the fairy-stroke.",
  "So the herb doctor was sent for, and every measure tried to save her, but without avail, for just as the moon rose that night, soft, low music was heard round the house, and when they looked at the woman she was dead.",
 }},
 {id="pd_demon_cat",title="The Demon Cat",premise="",zone="Westfall coast",edition="public-domain",openingMode="emote",emotes={},introductions={},lines={
  "There was a woman in Westfall, the wife of a fisherman, and as he always had very good luck, she had plenty of fish at all times stored away in the house ready for market.",
  "But to her great annoyance she found that a great cat used to come in at night and devour all the best and finest fish. So she kept a big stick by her and determined to watch.",
  "One day, as she and a woman were spinning together, the house suddenly became quite dark; and the door was burst open as if by the blast of the tempest, when in walked a huge black cat, who went straight up to the fire, then turned round",
  "and growled at them. \"Why, surely this is the devil!\" said a young girl, who was by, sorting the fish. \"I'll teach you how to call me names,\" said the cat; and, jumping at her, he scratched her arm till the blood came.",
  "\"There now,\" he said, \"you will be more civil another time when a gentleman comes to see you.\" And with that he walked over to the door and shut it close to prevent any of them going out, for the poor young girl, while crying loudly from",
  "fright and pain, had made a desperate rush to get away. Just then a man was going by, and hearing the cries he pushed open the door and tried to get in, but the cat stood on the threshold and would let no one pass.",
  "On this, the man attacked him with his stick, and gave him a sound blow; the cat, however, was more than his match in the fight, for it flew at him and tore his face and hands so badly that the man at last took to his heels and ran away as",
  "fast as he could. \"Now it's time for my dinner,\" said the cat, going up to examine the fish that was laid out on the tables. \"I hope the fish is good to-day.",
  "Now don't disturb me, nor make a fuss; I can help myself.\" With that he jumped up and began to devour all the best fish, while he growled at the woman.",
  "\"Away, out of this, you wicked beast!\" she cried, giving it a blow with the tongs that would have broken its back, only it was a devil; \"out of this!",
  "No fish shall you have to-day.\" But the cat only grinned at her, and went on tearing and spoiling and devouring the fish, evidently not a bit the worse for the blow.",
  "On this, both the women attacked it with sticks, and struck hard blows enough to kill it, on which the cat glared at them, and spit fire; then making a leap, it tore their hands and arms till the blood came, and the frightened women rushed",
  "shrieking from the house. But presently the mistress returned, carrying with her a bottle of holy water; and looking in, she saw the cat still devouring the fish, and not minding.",
  "So she crept over quietly and threw the holy water on it without a word. No sooner was this done than a dense black smoke filled the place, through which nothing was seen but the two red eyes of the cat, burning like coals of fire.",
  "Then the smoke gradually cleared away, and she saw the body of the creature burning slowly till it became shrivelled and black like a cinder, and finally disappeared.",
  "And from that time the fish remained untouched and safe from harm, for the power of the Evil One was broken, and the demon cat was seen no more.",
 }},
}
ns.RetiredStoryIds={["girl_beyond_firelight_v1"]=true,["elwynn_toll_01"]=true,["darkshore_nets_02"]=true,["ashenvale_watch_03"]=true,["duskwood_mason_04"]=true,["elwynn_oven_05"]=true,["darkshore_bell_06"]=true,["ashenvale_thread_07"]=true,["duskwood_lodger_08"]=true,["elwynn_bees_09"]=true,["darkshore_boots_10"]=true,["ashenvale_horn_11"]=true,["duskwood_wicks_12"]=true,["elwynn_mill_13"]=true,["darkshore_stones_14"]=true,["ashenvale_cup_15"]=true,["duskwood_ledger_16"]=true,["elwynn_apple_17"]=true,["darkshore_sail_18"]=true,["ashenvale_axe_19"]=true,["duskwood_mirror_20"]=true,["elwynn_horse_21"]=true,["darkshore_window_22"]=true,["ashenvale_deer_23"]=true,["duskwood_seam_24"]=true,["elwynn_well_25"]=true,["darkshore_fog_26"]=true,["ashenvale_names_27"]=true,["duskwood_coal_28"]=true,["elwynn_ribbon_29"]=true,["ashenvale_fire_30"]=true}
ns.StoryCredits={
 ["pd_golden_arm"]="Joseph Jacobs (collector)",
 ["pd_hand_of_glory"]="William Henderson (collector)",
 ["pd_dead_mother"]="W. R. S. Ralston (translator)",
 ["pd_frau_trude"]="Brothers Grimm; Margaret Hunt (translator)",
 ["pd_coffin_lid"]="W. R. S. Ralston (translator)",
 ["pd_sarah_polgrain"]="Robert Hunt (collector); WoW place names",
 ["pd_headless_princess"]="W. R. S. Ralston (translator)",
 ["pd_warlock"]="W. R. S. Ralston (translator)",
 ["pd_shroud"]="W. R. S. Ralston (translator)",
 ["pd_two_corpses"]="W. R. S. Ralston (translator)",
 ["pd_mr_miacca"]="Joseph Jacobs (collector)",
 ["pd_master_pupil"]="Joseph Jacobs (collector); WoW place names",
 ["pd_rose_tree"]="Joseph Jacobs (collector)",
 ["pd_death_sign"]="Lady Wilde (collector)",
 ["pd_dead_hand"]="Lady Wilde (collector)",
 ["pd_dead_soldier"]="Lady Wilde (collector); WoW place names",
 ["pd_lady_witch"]="Lady Wilde (collector); WoW place names",
 ["pd_fairy_changeling"]="Lady Wilde (collector)",
 ["pd_dance_dead"]="Lady Wilde (collector); WoW place names",
 ["pd_demon_cat"]="Lady Wilde (collector); WoW place names",
}
